version: '3'
services:
  shogo_laravel_back:
    container_name: 'shogo_laravel_back'
    build:
      context: '.docker/'
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - './project/:/var/www/project'

  shogo_laravel_nginx:
    container_name: 'shogo_laravel_nginx'
    image: nginx
    ports:
      - "88:80"
    volumes:
      - './.docker/nginxconf:/etc/nginx/conf.d'
      - './project/:/var/www/project'

  shogo_laravel_mysql:
    container_name: 'shogo_laravel_mysql'
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
        MYSQL_DATABASE: ${DB_DATABASE:-laraveldb}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-12345678}
        MYSQL_PASSWORD: ${DB_PASSWORD:-12345678}
        MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - shogo_mysqldb:/var/lib/mysql

volumes:
  shogo_mysqldb:
    driver: local
